TOPIC_RESOURCE_KIND = "Topic"
TOPIC_RESOURCE_PLURAL = 'topics'
SUBSCRIPTION_RESOURCE_PLURAL = 'subscriptions'
PLATFORM_ENDPOINT_RESOURCE_PLURAL = 'platformendpoints'
PLATFORM_APPLICATION_RESOURCE_PLURAL = 'platformapplications'
