// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package platform_endpoint

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.CustomUserData, b.ko.Spec.CustomUserData) {
		delta.Add("Spec.CustomUserData", a.ko.Spec.CustomUserData, b.ko.Spec.CustomUserData)
	} else if a.ko.Spec.CustomUserData != nil && b.ko.Spec.CustomUserData != nil {
		if *a.ko.Spec.CustomUserData != *b.ko.Spec.CustomUserData {
			delta.Add("Spec.CustomUserData", a.ko.Spec.CustomUserData, b.ko.Spec.CustomUserData)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Enabled, b.ko.Spec.Enabled) {
		delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
	} else if a.ko.Spec.Enabled != nil && b.ko.Spec.Enabled != nil {
		if *a.ko.Spec.Enabled != *b.ko.Spec.Enabled {
			delta.Add("Spec.Enabled", a.ko.Spec.Enabled, b.ko.Spec.Enabled)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.PlatformApplicationARN, b.ko.Spec.PlatformApplicationARN) {
		delta.Add("Spec.PlatformApplicationARN", a.ko.Spec.PlatformApplicationARN, b.ko.Spec.PlatformApplicationARN)
	} else if a.ko.Spec.PlatformApplicationARN != nil && b.ko.Spec.PlatformApplicationARN != nil {
		if *a.ko.Spec.PlatformApplicationARN != *b.ko.Spec.PlatformApplicationARN {
			delta.Add("Spec.PlatformApplicationARN", a.ko.Spec.PlatformApplicationARN, b.ko.Spec.PlatformApplicationARN)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Token, b.ko.Spec.Token) {
		delta.Add("Spec.Token", a.ko.Spec.Token, b.ko.Spec.Token)
	} else if a.ko.Spec.Token != nil && b.ko.Spec.Token != nil {
		if *a.ko.Spec.Token != *b.ko.Spec.Token {
			delta.Add("Spec.Token", a.ko.Spec.Token, b.ko.Spec.Token)
		}
	}

	return delta
}
